# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' build a vantage point tree
#' 
#' @param m \code{matrix}
#' @param k \code{integer} number of neighbors
#' @useDynLib vptree
#' @export
vptree <- function(m, k) {
    .Call('vptree_vptree', PACKAGE = 'vptree', m, k)
}

